### ISSUE TITLE
Add CI/CD pipeline to build a docker image

### ISSUE THREAD

**Issue by hectorj2f** [fabric8-ui/fabric8-ui-openshift-nginx#7]
We need an automatized manner of building this image and push it to the registry as done for other components.

I propose to add a Jenkins file to build the image and replace fabric8-ui Dockerfile to make use of this new image. WDYT @aslakknutsen ?

**Comment by hectorj2f** [comment]
@aslakknutsen or @joshuawilson I might need your admin privileges to set the webhook, as done for other repos.

**Comment by aslakknutsen** [comment]
Hopefully it's just picked up :)

**Comment by hectorj2f** [comment]
done!
